/**
 * Enum to represent type of Exception occurred in Application
 */

package org.openmrs.module.mobile.shared;

/**
 * @author owais.hussain@irdresearch.org
 * 
 */
public enum ErrorType
{
	AUTHENTICATION_ERROR, DATA_ACCESS_ERROR, DATA_CONNECTION_ERROR, DATA_MISMATCH_ERROR, DELETE_ERROR, DUPLICATION_ERROR, EMPTY_DATA_ERROR, INSERT_ERROR, INVALID_DATA_ERROR, ITEM_NOT_FOUND, PARAMETER_MISSING, PARSING_ERROR, SESSION_EXPIRED, UNKNOWN_ERROR, UPDATE_ERROR, USER_NOT_FOUND, USER_ROLE_UNDEFINED, VERSION_MISMATCH_ERROR

}